// Principais marcas de motocicletas comercializadas no Brasil.
export const MOTORCYCLE_BRANDS = [
  "Aprilia",
  "Bajaj",
  "BMW Motorrad",
  "BRM",
  "CFMoto",
  "Dafra",
  "Ducati",
  "Haojue",
  "Harley-Davidson",
  "Honda",
  "Indian Motorcycle",
  "Kawasaki",
  "KTM",
  "Moto Guzzi",
  "MV Agusta",
  "Royal Enfield",
  "Shineray",
  "Sundown",
  "Suzuki",
  "Traxx",
  "Triumph",
  "TVS",
  "Vespa (Piaggio)",
  "Voltz",
  "Yamaha",
  "Outra",
] as const;
